### ISSUE TITLE
How to set this?

### ISSUE THREAD

**Issue by gtnl** [MilesPong/indigo#2]
php artisan db:seed
Seeding: InitializationSeeder
Seeding: PermissionsTableSeeder
Seeding: RolesTableSeeder
Seeding: UsersTableSeeder
Seeding: CategoriesTableSeeder
Seeding: TagsTableSeeder
Seeding: PostsTableSeeder

In ClientContext.php line 116:
                                            
  AlgoliaSearch requires an applicationID.

**Comment by MilesPong** [comment]
Algolia driver is enabled by default in Laravel scout, so you may need an account of this service. Or just temporarily "fix" this by disabling the scout service with appending this configuration below to the end of `.env`

```
 SCOUT_DRIVER=null
